### ISSUE TITLE
latest release seems broken locally

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/internet-identity#2209]
when trying to use II locally via `dfx deps`, the frontend doen't load

![](https://files.slack.com/files-pri/T04JD4T1YRH-F06E9G1HWLW/screenshot_2024-01-18_at_12.21.26.png)

the same error occurs when using the latest II version with the "traditional" approach
```json
        "internet_identity_latest": {
          "type": "custom",
          "candid": "https://github.com/dfinity/internet-identity/releases/latest/download/internet_identity.did",
          "wasm": "https://github.com/dfinity/internet-identity/releases/latest/download/internet_identity_dev.wasm.gz",
          "remote": {
            "id": {
              "ic": "rdmx6-jaaaa-aaaaa-aaadq-cai"
            }
          }
        },
```

the error does not occur with an old release
```json
        "internet_identity_old": {
            "type": "custom",
            "candid": "https://github.com/dfinity/internet-identity/releases/download/release-2023-08-11/internet_identity.did",
            "wasm": "https://github.com/dfinity/internet-identity/releases/download/release-2023-08-11/internet_identity_dev.wasm.gz",
            "remote": {
                "id": {
                    "ic": "rdmx6-jaaaa-aaaaa-aaadq-cai"
                }
            }
        },
```

**Comment by frederikrothenberger** [comment]
This is because II was switched to multiple JS bundles recently, which means that query parameter based routing will no longer work. Please use canister id subdomains on Chrome and Firefox to access the local II canister: `http://<canisterId>.localhost:4943`

See [this section](https://github.com/dfinity/internet-identity#local-replica) in the top level readme as well.
